print("My name is Nababa Toyeebat.\nI am learning python")
print("Temidayo is in Abuja\tshe is a model")
print("He said, \"Hello\"")
print('It\'s Python!')
print("Welcome to Python\nLet's learn together!")
print("Name\tAge\tLocation")
print("Aisha\t25\tLagos")
print("She Said, \"Hello there!\"")
print('It\'s a sunny day.')
print("File path: C:\\Users\\Aisha\\Documents")
print("123456\rABC")
print("Yoo!!\b B.")
print("\a")
print("\t    *")
print("\t   ***")
print("\t  *****")
print("\t *******")
print("\t*********")
print("This a pyramid pattern i made")
print("\t    *\n\t   ***\n\t  *****\n\t *******\n\t*********")